[project]
name = "Helium"
version = "0.6.4"
description = "Let Sublime Text talk with Jupyter."
readme = "README.md"
license = "GPL-2.0-only"

[dependency-groups]
dev = [
	"black",
	"flake8",
]

[tool.black]
line-length = 88
target-version = ["py38"]
exclude = '''
/( \.git
 | \.venv
 | lib/client
 | tests
)/
'''

[tool.flake8]
ignore = "E203,D100,D101,D102,D103,D104,D105,D106,D107,D203,W503"
exclude = ".git,.venv,lib/client,tests"
max-line-length = 88
