name: CI
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.14

    steps:
    - uses: actions/checkout@v7
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v7
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install -U --disable-pip-version-check black flake8 flake8-blind-except flake8-comprehensions flake8-docstrings flake8-eradicate
    - name: Run linters
      run: |
        black --check .
        flake8 .
